# Generated by Django 4.0.6 on 2022-07-06 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid ip', message='must be ip adress x.x.x.x', regex='^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$')]),
        ),
        migrations.RemoveField(
            model_name='host',
            name='owners',
        ),
        migrations.AddField(
            model_name='host',
            name='owners',
            field=models.ManyToManyField(related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid port', message='must be port xxxx', regex='^\\d{0,10}$')]),
        ),
    ]
